index:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET

login:
    path: /login
    controller: App\Controller\LoginController::index
    methods: GET

connect_telegram_check:
    path: /login
    methods: POST

logout:
    path: /logout
    methods: GET

tasks:
    path: /tasks
    controller: App\Controller\TasksController::index
    methods: GET

tasks_all:
    path: /tasks/all
    controller: App\Controller\TasksController::all
    methods: GET

tasks_store:
    path: /tasks
    controller: App\Controller\TasksController::store
    methods: PUT

events_all:
    path: /events/all
    controller: App\Controller\EventsController::all
    methods: GET