index:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET

login:
    path: /login
    controller: App\Controller\LoginController::index
    methods: GET

post_login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: POST

tasks:
    path: /tasks
    controller: App\Controller\TasksController::index
    methods: GET